dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

matrix:
  include:
    - os: linux
    env: TARGET=rpm
    - os: linux
    env: TARGET=deb
    - os: osx
    env: TARGET=osx

script:
  - node index.js

branches:
  only:
    - master
